version: '3'
services:
  mongodb:
    build:
      context: ./mongo
      dockerfile: ./Dockerfile
    networks:
      - book-shop
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongodb-admin:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - book-shop
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}

  books:
    build:
      context: ./book
      dockerfile: ./Dockerfile
    ports:
      - 8082:8080
    # Local dev
    # volumes:
    #   - ./book/server.js:/var/www/server.js
    networks:
      - book-shop
    depends_on:
      - mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

networks:
  book-shop: